const mockData = [
    {
        id: 1,
        name: "Wireless Headphones",
        category: "Electronics",
        brand: "Brand A",
        price: 99.99,
        rating: 4.5,
        imageUrl: "https://placehold.co/600x400?text=WirelessHeadphones",
    },
    {
        id: 2,
        name: "Bluetooth Speaker",
        category: "Electronics",
        brand: "Brand B",
        price: 49.99,
        rating: 4.0,
        imageUrl: "https://placehold.co/600x400?text=BluetoothSpeaker",
    },
    {
        id: 3,
        name: "Running Shoes",
        category: "Footwear",
        brand: "Brand C",
        price: 59.99,
        rating: 4.2,
        imageUrl: "https://placehold.co/600x400?text=RunningShoes",
    },
    {
        id: 4,
        name: "Smartphone",
        category: "Electronics",
        brand: "Brand D",
        price: 499.99,
        rating: 4.8,
        imageUrl: "https://placehold.co/600x400?text=Smartphone",
    },
    {
        id: 5,
        name: "Leather Jacket",
        category: "Clothing",
        brand: "Brand E",
        price: 199.99,
        rating: 4.7,
        imageUrl: "https://placehold.co/600x400?text=LeatherJacket",
    },
    {
        id: 6,
        name: "Yoga Mat",
        category: "Sports",
        brand: "Brand F",
        price: 19.99,
        rating: 4.3,
        imageUrl: "https://placehold.co/600x400?text=YogaMat",
    },
    {
        id: 7,
        name: "Laptop",
        category: "Electronics",
        brand: "Brand G",
        price: 899.99,
        rating: 4.6,
        imageUrl: "https://placehold.co/600x400?text=Laptop",
    },
    {
        id: 8,
        name: "Mountain Bike",
        category: "Sports",
        brand: "Brand H",
        price: 299.99,
        rating: 4.9,
        imageUrl: "https://placehold.co/600x400?text=MountainBike",
    },
    {
        id: 9,
        name: "Digital Watch",
        category: "Accessories",
        brand: "Brand I",
        price: 79.99,
        rating: 4.1,
        imageUrl: "https://placehold.co/600x400?text=DigitalWatch",
    },
    {
        id: 10,
        name: "Gaming Console",
        category: "Electronics",
        brand: "Brand J",
        price: 399.99,
        rating: 4.4,
        imageUrl: "https://placehold.co/600x400?text=GamingConsole",
    },
    {
        id: 11,
        name: "Coffee Maker",
        category: "Home Appliances",
        brand: "Brand K",
        price: 89.99,
        rating: 4.2,
        imageUrl: "https://placehold.co/600x400?text=CoffeeMaker",
    },
    {
        id: 12,
        name: "Smart TV",
        category: "Electronics",
        brand: "Brand L",
        price: 699.99,
        rating: 4.6,
        imageUrl: "https://placehold.co/600x400?text=SmartTV",
    },
    {
        id: 13,
        name: "Electric Toothbrush",
        category: "Health & Beauty",
        brand: "Brand M",
        price: 29.99,
        rating: 4.3,
        imageUrl: "https://placehold.co/600x400?text=ElectricToothbrush",
    },
    {
        id: 14,
        name: "Trekking Backpack",
        category: "Outdoor Gear",
        brand: "Brand N",
        price: 59.99,
        rating: 4.5,
        imageUrl: "https://placehold.co/600x400?text=TrekkingBackpack",
    },
    {
        id: 15,
        name: "E-reader",
        category: "Electronics",
        brand: "Brand O",
        price: 129.99,
        rating: 4.4,
        imageUrl: "https://placehold.co/600x400?text=E-reader",
    },
];

export default mockData;
